name: Demo State Scan

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  run-checkov-scanner:
    name: Demo State Scan
    secrets: inherit
    uses: krakenteknologies/kt-workflows/.github/workflows/terraform-module-scanner.yaml@main
    with:
      scan_directory: .
      framework: terraform
      soft_fail: false